---
- name: Install & configure the misc applications
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install CLI applications available on DNF
      ansible.builtin.dnf:
        name:
          - bat # cat with color
          - perl-Image-ExifTool # manage EXIF of pictures
          - eza # better ls
          - fd-find # newer find
          - fzf # fuzzy finder
          - jpegoptim # compress jpeg pictures
          - lazygit # git TUI used by LazyVim
          - neovim # newer Vim
          - python3-neovim # Optional for Neovim
          - ripgrep # better grep
          - wl-clipboard # for wl-copy
          - zellij # terminal multiplexer - newer tmux
          - zoxide # better cd

    - name: Install Discord
      ansible.builtin.dnf:
        name: discord

    - name: Install Signal
      community.general.flatpak:
        name: org.signal.Signal

    - name: Install Kitty (terminal emulator)
      ansible.builtin.dnf:
        name: kitty

    - name: Install GIMP
      ansible.builtin.dnf:
        name: gimp

    - name: Install Kdenlive (FOSS video editor)
      ansible.builtin.dnf:
        name: kdenlive

    - name: Install Shotwell (photo gallery)
      ansible.builtin.dnf:
        name: shotwell
